name: Enhanced_COXEN
channels:
  - defaults
  - conda-forge
dependencies:
  - astropy=3.1.2
  - matplotlib=3.0.3
  - numpy=1.16.2
  - pandas=0.24.2
  - patsy=0.5.1
  - scikit-learn=0.21.2
  - scipy=1.2.1